# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercial_name', models.CharField(max_length=100, null=True, verbose_name='Nombre Comercial')),
                ('company_name', models.CharField(max_length=100, null=True, verbose_name='Raz\xf3n Social')),
                ('contact', models.CharField(max_length=100, null=True, verbose_name='Contacto')),
                ('financial_id', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='ID Fiscal')),
                ('financial_accounting_id', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='ID Fiscal Contable')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='static/img/', verbose_name='Logo')),
                ('slogan', models.CharField(blank=True, max_length=255, verbose_name='Eslogan')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='CompanyEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
            },
        ),
        migrations.CreateModel(
            name='CompanyPhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Tel\xe9fono')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Tel\xe9fono',
                'verbose_name_plural': 'Tel\xe9fonos',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='emails',
            field=models.ManyToManyField(blank=True, to='companies.CompanyEmail', verbose_name='Emails'),
        ),
        migrations.AddField(
            model_name='company',
            name='phone_numbers',
            field=models.ManyToManyField(blank=True, to='companies.CompanyPhoneNumber', verbose_name='N\xfameros de tel\xe9fono'),
        ),
    ]
