# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 22:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.CharField(max_length=255, verbose_name='Descripci\xf3n')),
                ('identifier', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(code='nomatch', message='El identificador debe ser de dos d\xedgitos', regex='^.{2}$')], verbose_name='Identificador de subcuenta')),
                ('movements', models.BooleanField(default=False, verbose_name='Acepta Movimiento?')),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='general.Company', verbose_name='Empresa')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Cuenta Mayor',
                'verbose_name_plural': 'Cat\xe1logo - 2 .Cuentas Mayores',
            },
        ),
        migrations.CreateModel(
            name='AccountCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.CharField(max_length=255, verbose_name='Descripci\xf3n')),
                ('identifier', models.CharField(max_length=1, verbose_name='Identificador')),
                ('nature', models.CharField(choices=[('deb', 'Debe'), ('hab', 'Haber')], default='deb', max_length=3, verbose_name='Naturaleza')),
                ('movements', models.BooleanField(default=False, verbose_name='Acepta Movimiento?')),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='general.Company', verbose_name='Empresa')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Tipo de Cuenta',
                'verbose_name_plural': 'Cat\xe1logo - 1 .Tipos de Cuentas',
            },
        ),
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.CharField(max_length=255, verbose_name='Descripci\xf3n')),
                ('identifier', models.CharField(max_length=1, verbose_name='Identificador')),
                ('movements', models.BooleanField(default=False, verbose_name='Acepta Movimiento?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.AccountCategory', verbose_name='Tipo de Cuenta')),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='general.Company', verbose_name='Empresa')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Grupo de Cuenta',
                'verbose_name_plural': 'Cat\xe1logo - 2 .Grupos de Cuentas',
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='general.Company', verbose_name='Empresa')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Cat\xe1logo',
                'verbose_name_plural': 'Cat\xe1logo',
            },
        ),
        migrations.CreateModel(
            name='DetailAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.CharField(max_length=255, verbose_name='Descripci\xf3n')),
                ('identifier', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(code='nomatch', message='El identificador debe ser de dos d\xedgitos', regex='^.{2}$')], verbose_name='Identificador de subcuenta')),
                ('movements', models.BooleanField(default=False, verbose_name='Acepta Movimiento?')),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='general.Company', verbose_name='Empresa')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Cuenta Detalle',
                'verbose_name_plural': 'Cat\xe1logo - 4 Cuentas Detalle',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('entyDate', models.DateField(null=True, verbose_name='Fecha del asiento')),
                ('detail', models.CharField(max_length=255, verbose_name='Detalle')),
                ('totalDebit', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Total Debe')),
                ('totalCredit', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Total Haber')),
                ('difference', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Diferencia')),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='general.Company', verbose_name='Empresa')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Asiento',
                'verbose_name_plural': 'Asientos',
            },
        ),
        migrations.CreateModel(
            name='EntryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Debe')),
                ('credit', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Haber')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account', verbose_name='Cuenta')),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='general.Company', verbose_name='Empresa')),
                ('detailAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.DetailAccount', verbose_name='Cuenta Detalle')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Entry', verbose_name='Asiento')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Detalle de Asiento',
                'verbose_name_plural': 'Asientos - 1 .Detalles de Asiento',
            },
        ),
        migrations.CreateModel(
            name='SubAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.CharField(max_length=255, verbose_name='Descripci\xf3n')),
                ('identifier', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(code='nomatch', message='El identificador debe ser de dos d\xedgitos', regex='^.{2}$')], verbose_name='Identificador de subcuenta')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Account', verbose_name='Cuenta Mayor')),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='general.Company', verbose_name='Empresa')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Sub-Cuenta',
                'verbose_name_plural': 'Cat\xe1logo - 3 .Sub-Cuentas',
            },
        ),
        migrations.AddField(
            model_name='entrydetail',
            name='subAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.SubAccount', verbose_name='Sub-Cuenta'),
        ),
        migrations.AddField(
            model_name='detailaccount',
            name='subaccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.SubAccount', verbose_name='Sub-Cuenta'),
        ),
        migrations.AddField(
            model_name='account',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.AccountGroup', verbose_name='Grupo de Cuenta'),
        ),
    ]
