# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-27 14:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20170223_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='group',
        ),
        migrations.AddField(
            model_name='account',
            name='level',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9, message='nivel debe ser menor de un solo d\xedgito')], verbose_name='Nivel de la cuenta'),
        ),
        migrations.AddField(
            model_name='account',
            name='nature',
            field=models.CharField(choices=[('deb', 'Debe'), ('hab', 'Haber')], default='deb', max_length=3, verbose_name='Naturaleza'),
        ),
        migrations.AddField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Account', verbose_name='Cuenta Padre'),
        ),
        migrations.AlterField(
            model_name='subaccount',
            name='identifier',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(code='nomatch', message='El identificador debe ser de dos d\xedgitos', regex='^.{2}$')], verbose_name='Identificador de subcuenta'),
        ),
    ]
