# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-27 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20170227_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Cuenta Activa?'),
        ),
    ]
