# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 23:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_account_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['id'], 'verbose_name': 'Cuenta Contable', 'verbose_name_plural': 'Cat\xe1logo - 1. Cuentas Contables'},
        ),
        migrations.AlterField(
            model_name='account',
            name='identifier',
            field=models.CharField(max_length=3, verbose_name='Identificador'),
        ),
        migrations.AlterField(
            model_name='account',
            name='level',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9, message='nivel debe ser de un solo d\xedgito')], verbose_name='Nivel de la cuenta'),
        ),
    ]
