# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 23:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_auto_20170301_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='description',
        ),
    ]
