# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-13 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
        ('accounting', '0007_remove_account_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('level', models.PositiveIntegerField(verbose_name='Nivel de cuenta')),
                ('identifierDigits', models.PositiveIntegerField(default=1)),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='general.Company', verbose_name='Empresa')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Nivel de Cuenta',
                'verbose_name_plural': 'Cat\xe1logo - 2. Niveles de Cuenta',
            },
        ),
        migrations.AlterField(
            model_name='account',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.AccountLevel', verbose_name='Nivel de la Cuenta'),
        ),
        migrations.AlterUniqueTogether(
            name='accountlevel',
            unique_together=set([('company', 'level')]),
        ),
    ]
