# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-17 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_auto_20170313_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='detail',
        ),
        migrations.AddField(
            model_name='entrydetail',
            name='detail',
            field=models.CharField(default='hola', max_length=255, verbose_name='Detalle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='entrydetail',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Company', verbose_name='Empresa'),
        ),
    ]
