# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-17 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_auto_20170317_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='entyDate',
            new_name='entryDate',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='totalDebit',
            new_name='totalDebe',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='totalCredit',
            new_name='totalHaber',
        ),
        migrations.RenameField(
            model_name='entrydetail',
            old_name='debit',
            new_name='debe',
        ),
        migrations.RenameField(
            model_name='entrydetail',
            old_name='credit',
            new_name='haber',
        ),
    ]
