# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-17 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_auto_20170317_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrydetail',
            name='document',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Docuento'),
        ),
        migrations.AlterField(
            model_name='entrydetail',
            name='detail',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Detalle'),
        ),
    ]
