# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-17 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
        ('accounting', '0011_auto_20170317_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('header', models.CharField(max_length=255, verbose_name='Encabezado')),
                ('template', models.CharField(choices=[('tmp1', 'Plantilla 1'), ('tmp2', 'Plantilla 2')], max_length=4, verbose_name='Plantilla')),
                ('accountsToShow', models.ManyToManyField(to='accounting.Account', verbose_name='Cuentas a mostrar')),
                ('accountsToSum', models.ManyToManyField(to='accounting.Account', verbose_name='Cuentas a sumar')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Company', verbose_name='Empresa')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
            },
        ),
    ]
