# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('companies', '0001_initial'),
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_num', models.PositiveIntegerField(verbose_name='Consecutivo')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Subtotal')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Descuento')),
                ('exempt', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Excento')),
                ('with_tax', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Gravado')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Impuestos')),
                ('total', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='Cliente')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company', verbose_name='Empresa')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.Currency', verbose_name='Moneda')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Factura de Venta',
                'verbose_name_plural': 'Facturas de Venta',
            },
        ),
        migrations.CreateModel(
            name='SaleBillDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.PositiveIntegerField(verbose_name='C\xf3digo del producto')),
                ('qty', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('description', models.CharField(max_length=255, verbose_name='Descripci\xf3n')),
                ('use_taxes', models.BooleanField(default=False, verbose_name='Excento o Gravado?')),
                ('tax_percentage', models.FloatField(verbose_name='Porcentaje de Impuestos')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Subtotal')),
                ('sale_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saleBills.SaleBill', verbose_name='Factura de Venta')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Detalle de Factura',
                'verbose_name_plural': 'Detalles de Factura',
            },
        ),
    ]
