# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Periodo Fiscal')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Periodo Fiscal',
                'verbose_name_plural': 'Periodos Fiscales',
            },
        ),
    ]
