# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(default=0, verbose_name='C\xf3digo')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Descripci\xf3n del producto')),
                ('useinventory', models.BooleanField(default=False, verbose_name='Sistema de Inventarios?')),
                ('minimum', models.FloatField(default=0, verbose_name='M\xednimo en inventario')),
                ('unit', models.CharField(max_length=4, null=True, verbose_name='Unidad')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo \u20a1')),
                ('isactive', models.BooleanField(default=True, verbose_name='Activo?')),
                ('hasforsale', models.BooleanField(default=False, verbose_name='Es para Venta?')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company', verbose_name='Compa\xf1\xeda')),
            ],
            options={
                'ordering': ['code'],
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='ProductDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la Familia')),
                ('code', models.CharField(max_length=2, verbose_name='Identificador de Familia')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company', verbose_name='Compa\xf1\xeda')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Familia',
                'verbose_name_plural': 'Familias',
            },
        ),
        migrations.CreateModel(
            name='ProductForSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(default=0, verbose_name='C\xf3digo')),
                ('barcode', models.PositiveIntegerField(blank=True, default=0, verbose_name='C\xf3digo de Barras')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Descripci\xf3n del producto')),
                ('unit', models.CharField(max_length=4, null=True, verbose_name='Unidad')),
                ('utility', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Utilidad %')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio sin Impuestos \u20a1')),
                ('usetaxes', models.BooleanField(default=False, verbose_name='Usa Impuestos?')),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Impuestos %')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Descuento %')),
                ('sellprice', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio de Venta \u20a1')),
                ('isactive', models.BooleanField(default=True, verbose_name='Activo?')),
                ('iscomposed', models.BooleanField(default=False, verbose_name='Es Compuesto?')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company', verbose_name='Compa\xf1\xeda')),
                ('department', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ProductDepartment', verbose_name='Familia')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_product', to='products.Product', verbose_name='Producto')),
            ],
            options={
                'ordering': ['code'],
                'verbose_name': 'Producto para la Venta',
                'verbose_name_plural': 'Productos para la Venta',
            },
        ),
        migrations.CreateModel(
            name='ProductSubDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la Sub-Familia')),
                ('code', models.CharField(max_length=2, verbose_name='Identificador de Sub-Familia')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ProductDepartment', verbose_name='Familia')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Sub-Familia',
                'verbose_name_plural': 'Sub-Familias',
            },
        ),
        migrations.AddField(
            model_name='productforsale',
            name='subdepartment',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ProductSubDepartment', verbose_name='Sub-Familia'),
        ),
        migrations.AddField(
            model_name='product',
            name='department',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ProductDepartment', verbose_name='Familia'),
        ),
        migrations.AddField(
            model_name='product',
            name='subdepartment',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ProductSubDepartment', verbose_name='Sub-Familia'),
        ),
        migrations.AlterUniqueTogether(
            name='productsubdepartment',
            unique_together=set([('department', 'code'), ('department', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='productforsale',
            unique_together=set([('company', 'barcode'), ('company', 'code')]),
        ),
        migrations.AlterUniqueTogether(
            name='productdepartment',
            unique_together=set([('company', 'name'), ('company', 'code')]),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([('company', 'code')]),
        ),
    ]
