# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Moneda')),
                ('symbol', models.CharField(max_length=3, verbose_name='S\xedmbolo')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
            },
        ),
    ]
