# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercial_name', models.CharField(max_length=100, null=True, verbose_name='Nombre Comercial')),
                ('company_name', models.CharField(max_length=100, null=True, verbose_name='Raz\xf3n Social')),
                ('financial_id', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='ID Fiscal')),
                ('financial_accounting_id', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='ID Fiscal Contable')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='static/img/', verbose_name='Logo')),
                ('slogan', models.CharField(blank=True, max_length=255, verbose_name='Eslogan')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='CompanyEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Email',
                'verbose_name_plural': 'Empresas 2. Emails',
            },
        ),
        migrations.CreateModel(
            name='CompanyPhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Tel\xe9fono')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Tel\xe9fono',
                'verbose_name_plural': 'Empresas 1. Tel\xe9fonos',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Direcci\xf3n')),
                ('phone1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tel\xe9fono principal')),
                ('phone2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tel\xe9fono 2')),
                ('phone3', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tel\xe9fono 3')),
                ('email1', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email principal')),
                ('email2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email 2')),
                ('email3', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email 3')),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='general.Company', verbose_name='Empresa')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Contacto',
                'verbose_name_plural': ' Contactos',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Moneda')),
                ('code', models.CharField(max_length=3, verbose_name='Identificador')),
                ('symbol', models.CharField(max_length=3, verbose_name='S\xedmbolo')),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='general.Company', verbose_name='Empresa')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='emails',
            field=models.ManyToManyField(blank=True, to='general.CompanyEmail', verbose_name='Emails'),
        ),
        migrations.AddField(
            model_name='company',
            name='phone_numbers',
            field=models.ManyToManyField(blank=True, to='general.CompanyPhoneNumber', verbose_name='N\xfameros de tel\xe9fono'),
        ),
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together=set([('company', 'code')]),
        ),
    ]
