# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20161224_0859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='isSingle',
            new_name='isComposed',
        ),
    ]
