# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20161224_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='isComposed',
            field=models.BooleanField(default=True, verbose_name='Producto compuesto?'),
        ),
    ]
